---
- name: Converge
  hosts: localhost
  connection: local

  tasks:
    - name: "Include ansible-module"
      include_role:
        name: "ansible-module"

    - name: read variables from the environment that are set in the molecule.yml
      set_fact:
        ansible_host: "{{ lookup('env', 'TETRATION_SERVER_ENDPOINT') }}"
        api_key: "{{ lookup('env', 'TETRATION_API_KEY') }}"
        api_secret: "{{ lookup('env', 'TETRATION_API_SECRET') }}"
      no_log: True

    - name: put the variables in the required format
      set_fact:
        provider_info:
          api_key: "{{ api_key }}"
          api_secret: "{{ api_secret }}"
          server_endpoint: "{{ ansible_host }}"
      no_log: True

    - name: set test variables
      set_fact:
        root_scope: "{{ lookup('env', 'TETRATION_ROOT_SCOPE_NAME') }}"
        root_scope_id: "{{ lookup('env', 'TETRATION_ROOT_SCOPE_ID') }}"
    # -----
    - name: Find a software agent
      tetration_software_agent_query:
        host_name_contains: test-sensor
      register: agent_list

    - name: Test - Pull Software Agent Info
      tetration_software_agent:
        uuid: "{{ agent_list.object[0].uuid }}"
        state: query
        provider: "{{ provider_info }}"
      register: output

    - name: Verify - Pull Software Agent Info
      assert:
        that:
          - output.object.uuid == agent_list.object[0].uuid
