namespace: cisco
name: secureworkload
version: 1.0.4
readme: README.md
authors:
  - Karmanya Dadhich
  - Jeroen Wittock
description: A collection for automating Cisco Secure Workload
license_file: "LICENSE"
tags:
  - cisco
  - secure
  - workload
  - secure_workload
  - tetration
  - security
build_ignore:
  - "*tar.gz"
  - "*.DS_Store"
  - "*.json"
  - "venv*"
  - ".vscode"
  - ".gitignore"
  - ".env"
  - ".github"
  - "tests/output/"
  - "galaxy.yml"
  - "*.pyc"
  - ".git"
dependencies: {}
repository: https://github.com/CiscoDevNet/ansible-secure-workload
documentation: https://developer.cisco.com/learning/tracks/cisco-app-first-security/cisco-secure-workload-ansible/ansible-intro/step/1
homepage: https://github.com/CiscoDevNet/ansible-secure-workload
issues: https://github.com/CiscoDevNet/ansible-secure-workload/issues
