---
- name: Converge
  hosts: localhost
  connection: local

  tasks:
    - name: "Include ansible-module"
      include_role:
        name: "ansible-module"

    - name: read variables from the environment that are set in the molecule.yml
      set_fact:
        ansible_host: "{{ lookup('env', 'TETRATION_SERVER_ENDPOINT') }}"
        api_key: "{{ lookup('env', 'TETRATION_API_KEY') }}"
        api_secret: "{{ lookup('env', 'TETRATION_API_SECRET') }}"
      no_log: True 

    - name: put the variables in the required format
      set_fact:
        provider_info:
          api_key: "{{ api_key }}"
          api_secret: "{{ api_secret }}"
          server_endpoint: "{{ ansible_host }}"
      no_log: True 

    - name: set test variables
      set_fact:
        root_scope_id: 5ce71503497d4f2c23af85b7
# -----

    - name: Create an agent config profile
      tetration_software_agent_config_profile:
        name: test_agent_config_profile
        root_app_scope_id: "{{ root_scope_id }}"
        state: present
        provider: "{{ provider_info }}"
      register: output

    - name: Store config profile id
      set_fact:
        profile_id: "{{ output.object.id }}"
# ----- 

    - name: Test - Look for a missing config intent
      tetration_software_agent_config_intent:
        profile_name: test_agent_config_profile
        filter_id: "{{ root_scope_id }}"
        state: query 
        provider: "{{ provider_info }}"
      register: output
    
    - name: Output - Look for a missing config intent
      debug:
        var: output

    - name: Verify - Look for a missing config intent
      assert:
        that:
          - output.changed is false
          - output.failed is false
          - output.object | length == 0
# ----- 

    - name: Test - Create config intent
      tetration_software_agent_config_intent:
        profile_name: test_agent_config_profile
        filter_id: "{{ root_scope_id }}"
        state: present 
        provider: "{{ provider_info }}"
      register: output
    
    - name: Output - Create config intent
      debug:
        var: output

    - name: Verify - Create config intent
      assert:
        that:
          - output.changed is true 
          - output.failed is false
          - output.object.id is defined
          - output.object.inventory_config_profile_id == profile_id
          - output.object.inventory_filter_id == root_scope_id

# ----- 

    - name: Test - Query config intent
      tetration_software_agent_config_intent:
        profile_id: "{{ profile_id }}" 
        filter_id: "{{ root_scope_id }}"
        state: query 
        provider: "{{ provider_info }}"
      register: output
    
    - name: Output - Query config intent
      debug:
        var: output

    - name: Verify - Query config intent
      assert:
        that:
          - output.changed is false 
          - output.failed is false
          - output.object.id is defined 
          - output.object.inventory_config_profile_id == profile_id
          - output.object.inventory_filter_id == root_scope_id

# ----- 

    - name: Test - Verify config intent created
      tetration_software_agent_config_intent:
        profile_id: "{{ profile_id }}" 
        filter_id: "{{ root_scope_id }}"
        state: present 
        provider: "{{ provider_info }}"
      register: output
    
    - name: Output - Verify config intent created
      debug:
        var: output

    - name: Verify - Verify config intent created
      assert:
        that:
          - output.changed is false 
          - output.failed is false
          - output.object.id is defined 
          - output.object.inventory_config_profile_id == profile_id
          - output.object.inventory_filter_id == root_scope_id
# ----- 

    - name: Test - Delete config intent
      tetration_software_agent_config_intent:
        profile_id: "{{ profile_id }}" 
        filter_id: "{{ root_scope_id }}"
        state: absent 
        provider: "{{ provider_info }}"
      register: output
    
    - name: Output - Delete config intent
      debug:
        var: output

    - name: Verify - Delete config intent
      assert:
        that:
          - output.changed is true 
          - output.failed is false
          - output.object.success is true
# ----- 

    - name: Test - Delete config intent already deleted
      tetration_software_agent_config_intent:
        profile_id: "{{ profile_id }}" 
        filter_id: "{{ root_scope_id }}"
        state: absent 
        provider: "{{ provider_info }}"
      register: output
    
    - name: Output - Delete config intent already deleted
      debug:
        var: output

    - name: Verify - Delete config intent already deleted
      assert:
        that:
          - output.changed is false
          - output.failed is false
          - output.object | length == 0

# -----

    - name: Delete created agent config profile
      tetration_software_agent_config_profile:
        name: test_agent_config_profile
        root_app_scope_id: "{{ root_scope_id }}"
        state: absent 
        provider: "{{ provider_info }}"
      register: output
