---
- name: Converge
  hosts: localhost
  connection: local

  tasks:
    - name: "Include ansible-module"
      include_role:
        name: "ansible-module"
    
    - name: "set facts"
      set_fact:
        ansible_host: "https://ignwpov.tetrationpreview.com"
    - name: "Find a user"
      tetration_user:
        provider:
          api_key: "{{ api_key }}"
          api_secret: "{{ api_secret }}"
          server_endpoint: "{{ ansible_host }}"
        email: ericj@ignw.io
        state: query
      delegate_to: localhost
      register: output
    - name: debug
      debug:
        var: output
      