---
- name: Converge
  hosts: localhost
  connection: local

  tasks:
    - name: "Include ansible-module"
      include_role:
        name: "ansible-module"

    - name: read variables from the environment that are set in the molecule.yml
      set_fact:
        ansible_host: "{{ lookup('env', 'TETRATION_SERVER_ENDPOINT') }}"
        api_key: "{{ lookup('env', 'TETRATION_API_KEY') }}"
        api_secret: "{{ lookup('env', 'TETRATION_API_SECRET') }}"
      no_log: True

    - name: put the variables in the required format
      set_fact:
        provider_info:
          api_key: "{{ api_key }}"
          api_secret: "{{ api_secret }}"
          server_endpoint: "{{ ansible_host }}"
      no_log: True

    - name: set test variables
      set_fact:
        root_scope: "{{ lookup('env', 'TETRATION_ROOT_SCOPE_NAME') }}"
        root_scope_id: "{{ lookup('env', 'TETRATION_ROOT_SCOPE_ID') }}"
        test_app_id: 5ed69642755f027a324bd922
    # -----

    - name: Test - Search by IP Address
      tetration_inventory_tag_search:
        root_scope_name: "{{ root_scope }}"
        ip_address: 10.20.30.40
        provider: "{{ provider_info }}"
      register: output

    - name: Output - Search by IP Address
      debug:
        var: output

    - name: Verify - Search by IP Address
      assert:
        that:
          - output.failed is false
          - output.changed is false
    # -----

    - name: Test - Search by IP Subnet
      tetration_inventory_tag_search:
        root_scope_name: "{{ root_scope }}"
        ip_subnet: 10.0.0.0/8
        provider: "{{ provider_info }}"
      register: output

    - name: Output - Search by IP Subnet
      debug:
        var: output

    - name: Verify - Search by IP Subnet
      assert:
        that:
          - output.failed is false
          - output.changed is false
